FROM python:3.8.3-alphine
# MenuRoma is the maintainer of the project and image.
LABEL maintainer="MenuRoma"

# Environment variable setup in docker image.

# Tells python to run in unbuffered mode, this allows python
# to print directly rather to hold in buffer
ENV PYTHONUNBUFFERED 1


# Configuring the dependencies for the project
# Gets the
COPY ./requirements.txt /requirements.txt
