# .github/workflows/release.yml
name: Release
on:
  push:
    branches:
      - master
jobs:
  # lint:
  #   name: Commit Lint
  #   runs-on: ubuntu-latest
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.RECIPE_APP_API2_SECRET }}
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: "10.x"
  #     - run: npm install
  #     - name: Add dependencies for commitlint action
  #       # $GITHUB_WORKSPACE is the path to your repository
  #       run: echo "::set-env name=NODE_PATH::$GITHUB_WORKSPACE/node_modules"
  #     # Now the Commitlint action will run considering its own dependencies and yours as well 🚀
  #     - uses: wagoid/commitlint-github-action@v1
  #     - uses: ./
  #       with:
  #         configFile: "./.commitlint.config.js"
  release:
    name: Release
    # needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RECIPE_APP_API2_SECRET }}
        run: npx semantic-release
